### ISSUE TITLE
Enable allstar and scorecards in the top 10 critical projects of dart-lang

### ISSUE THREAD

**Issue by godofredoc** [dart-lang/.github#16]
@hixie and @godofredoc have been enabling allstar and scorecards for the flutter org and we can help enabling them for dart-lang.

To be able to do that we need org admins help to create a private project called .allstar and grant @hixie and godofredoc@ contributor access to it to be able to send a PR for the configurations.

Scorecards require a per project configuration and a personal access token stored as `SCORECARD_READ_TOKEN` in every project scorecards will be installed on. The token should have the following permissions `public_repo, read:discussion, read:org, read:repo_hook`.

The projects we are planning to enable scorecards are:

* [github.com/dart-lang/sdk](http://github.com/dart-lang/sdk)
* [github.com/dart-lang/linter](http://github.com/dart-lang/linter)
* [github.com/dart-lang/dartdoc](http://github.com/dart-lang/dartdoc)
* [github.com/dart-lang/site-www](http://github.com/dart-lang/site-www)
* [github.com/dart-lang/test](http://github.com/dart-lang/test)

**Comment by athomas** [comment]
dart-lang/.allstar is created now.

github.com/dart-lang/sdk,"Google,criticality_score:0.818810"

Do we actually need the SCORECARD_READ_TOKEN for these projects? They are all public and already seem to be enabled on scorecard:
https://raw.githubusercontent.com/ossf/scorecard/main/cron/data/projects.csv

Also, the dart-lang/sdk is GoB first, so only external contributors use PRs (in case that matters).

**Comment by godofredoc** [comment]
Yes, the token is needed to read project configurations like branch protection and allow writing to the security alerts API. Scorecards performs several checks apart from calculating the criticality score. e.g. this is the report for flutter/engine: 

https://github.com/flutter/engine/security/code-scanning

**Comment by godofredoc** [comment]
Awesome, thanks @athomas

**Comment by godofredoc** [comment]
Now that the token is ready we can copy https://github.com/flutter/flutter/blob/master/.github/workflows/scorecards-analysis.yml to the .github/workflows folders of the projects listed in this bug. Once the PRs are ready please add @athomas and @whesse as reviewers.

Note: we'll need to update the branch name to match the default branch of the repositories.

**Comment by mit-mit** [comment]
Anything remaining here?

**Comment by godofredoc** [comment]
Scorecards have been enabled in all the listed repositories. I'll close this one and I'll open individual bugs to track the scorecard alerts.
