### ISSUE TITLE
enable branch protection for protection for package:intl and package:intl_translation

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/.github#20]
See https://github.com/dart-lang/.allstar/issues/108 (and https://github.com/dart-lang/.allstar/issues/106); we'd like branch protection for https://github.com/dart-lang/intl and https://github.com/dart-lang/intl_trnaslation.

**Comment by athomas** [comment]
Closing this specific request, we'll address this org-wide with dart-lang/.allstar#230.
