### ISSUE TITLE
check team setup for 2 repos

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/.github#22]
I'm unable to run some graphql queries against two repos in dart-lang:

- dart-lang/lints
- ~dart-lang/yaml_edit~

I'd be worth checking to see who has write permissions there - whether they're set up with the `dart-team` team.

**Comment by kevmoo** [comment]
yaml_edit is set up to be maintained by `dart-team` 🤷

**Comment by devoncarew** [comment]
Hmm, thanks for checking; perhaps I was hitting some other issue at the time.

**Comment by athomas** [comment]
@devoncarew Looking at the GitHub actions runs it looks like one was started around the time you uploaded the PR. Maybe it just didn't show up in the UI?

I don't see anything wrong with the permissions, and I did go through all repos recently and ensured that dart-team has at least Write access (with the possible exception of a few special repos). So I'm closing this.
