### ISSUE TITLE
change the merge defaults for https://github.com/dart-lang/oauth2

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/.github#24]
https://github.com/dart-lang/oauth2 is currently set up to merge all commits from a PR by default. The recent repo history is a bit hard to read; I think we should disable that option - prefer squashing.

**Comment by devoncarew** [comment]
Or, is there a way to have 'squash and merge' be the default for dart-lang/?

**Comment by athomas** [comment]
I updated oauth2, note there's no "default" setting anywhere (that I could find), you can just disable the other options which is what I did. I didn't find a way to configure this org-wide.
