### ISSUE TITLE
Check the team status for https://github.com/dart-lang/dartdoc/

### ISSUE THREAD

**Issue by keertip** [dart-lang/.github#27]
I cannot commit to the dartdoc repo. Could you change access rights to `dart-team`?

**Comment by keertip** [comment]
@athomas , not sure who is responsible for this? Can you triage? Thanks!

**Comment by mit-mit** [comment]
This has Write access to dart-team. @keertip are you still seeing an issue?

**Comment by athomas** [comment]
I'm going to close this. Please re-open if still an issue.
