### ISSUE TITLE
Fix scorecard alerts for dart-lang / linter

### ISSUE THREAD

**Issue by godofredoc** [dart-lang/.github#31]
* Fix Alerts:
    * Token permissions
    * Pinned dependencies
* Add scorecards badge

**Comment by devoncarew** [comment]
I'm curious - where are you seeing the scorecard results?

**Comment by godofredoc** [comment]
I'm using the security tab and code scanning option: https://github.com/dart-lang/linter/security/code-scanning

**Comment by godofredoc** [comment]
![image](https://user-images.githubusercontent.com/54371434/194145730-8de95dfe-f6c1-4b80-bebb-d8a2b7ed5945.png)

**Comment by devoncarew** [comment]
cc @pq

**Comment by pq** [comment]
See: https://github.com/dart-lang/linter/pull/3751.

**Comment by pq** [comment]
See also https://github.com/dart-lang/linter/pull/3750.  Thanks @devoncarew!

**Comment by godofredoc** [comment]
https://github.com/dart-lang/linter/pull/3754 for adding the badge. Unfortunately I don't have permissions to add reviewers.

**Comment by godofredoc** [comment]
Thanks @pq and @devoncarew, closing this bug as completed.
