### ISSUE TITLE
Fix scorecard alerts in dart-lang / test

### ISSUE THREAD

**Issue by godofredoc** [dart-lang/.github#32]
* Fix the following alerts:
    * Dependency update tool
* Add scorecards badge

**Comment by devoncarew** [comment]
cc @natebosch (the detailed issues can be seen here: https://github.com/dart-lang/test/security/code-scanning).

**Comment by natebosch** [comment]
@kevmoo - what is our current best practice for dependabot and mono_repo?

**Comment by kevmoo** [comment]
I try to roll mono_repo ~monthly. In did it a bit earlier because of a node deprecation.

What more do we think we need?

**Comment by natebosch** [comment]
This alert indicates that we should be adding dependabot config to the test repo - however adding it would conflict with the updates done by `mono_repo`. So I think it's better to not raise this repo as an issue.

**Comment by godofredoc** [comment]
I see, in that case I'd recommend to ignore the alert. Let me send a PR to add the scorecards badge.

**Comment by godofredoc** [comment]
https://github.com/dart-lang/test/pull/1774 is ready unfortunately I have no write access to assign reviewers.
